### ISSUE TITLE
Some confusion over package manager features in the README:

### ISSUE THREAD

**Issue by iarna** [rksm/flatn#4]
Regarding Yarn:

_It uses a local cache to avoid downloading dependencies multiple times_

This is true. This is also true of every version of npm. Plus every verison of ied and pnpm, so this seems like a very weird thing call out. It's like advertising that your orange juice now includes H20.

 _on install links the dependencies required by the projects into node_modules folders._

Yarn does not link, it copies. Maybe you were thinking of pnpm which links or ied which symlinks?

**Comment by rksm** [comment]
Thank you for your feedback, I'll find a more precise wording.

And also thanks for all the hard work on npm!  I realize this stuff here might seem to be critical of it but npm is amazing, few people can say to have created an ecosystem.  Without it we wouldn't be here :)

**Comment by iarna** [comment]
Sooo, I hate to be jumping back in with another "but…", but well… now you're saying:

> Through parallelization it is faster than npm

The problem with this is that it's exactly as parallel as npm. (Older versions of npm didn't run install scripts in parallel, but npm@5 has had that for quite some time.)

Also, due to npm being very close to the same speed as yarn, you can't easily point at one thing as a reason for that, there are a few things that stand out though: First, yarn doesn't support bundled dependencies and the infrastructure needed to make them work adds overhead (though there's quite a bit of room for improvement there). Second, yarn doesn't check shasums when installing from its cache (npm does). And finally, npm rewrites all of the package.json's in all installed modules to include a variety of diagnostic information. This diagnostic info also allows npm to build a lock-file from an already installed folder, something yarn can't do.

**Comment by rksm** [comment]
My apologies.  The focus of the comparison are only the strategies for dealing with (shared) dependencies of local packages and alternatives to node.js' default module lookup strategy.

I removed mentioning parallelization as this is irrelevant in that regard.  Let me know if you want me to make other changes.
